language: go
sudo: false
go:
  - 1.6
  - 1.7
install:  
  - go get -u -t github.com/onsi/ginkgo
  - go get -u -t github.com/onsi/gomega  
script:
  - echo "TRAVIS_BUILD_DIR is "$TRAVIS_BUILD_DIR
  - cp -r $TRAVIS_BUILD_DIR/algorithmutil $HOME/gopath/src/algorithmutil  
  - cp -r $TRAVIS_BUILD_DIR/abstract $HOME/gopath/src/abstract
  - cd sort && go test && cd ..