language: go
sudo: false
go:
  - 1.6
  - 1.7
install:  
  - go get -u -t github.com/onsi/ginkgo
  - go get -u -t github.com/onsi/gomega
  - go get -u -t github.com/ilovelili/Algorithms/sort
  - go get -u -t github.com/ilovelili/Algorithms/algorithmutil
script:
  - cd sort && go test && cd ..