language: go
sudo: false
go:
  - 1.6
  - 1.7
install:  
  - go get -u -t github.com/onsi/ginkgo
  - go get -u -t github.com/onsi/gomega  
script:
  - echo "dir is "$TRAVIS_BUILD_DIR
  - ln -s $GOPATH/src/github.com/ilovelili/algorithmutil  $TRAVIS_BUILD_DIR/algorithmutil
  - cd sort && go test && cd ..